CREATE TABLE IF NOT EXISTS INGREDIENT (
  id VARCHAR(4) UNIQUE NOT NULL,
  name VARCHAR(25) NOT NULL,
  type VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS TACO (
  id BIGINT UNIQUE GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TACO_INGREDIENTS (
  taco_id BIGINT NOT NULL,
  ingredients_id VARCHAR(4) NOT NULL
);

ALTER TABLE TACO_INGREDIENTS ADD FOREIGN KEY (taco_id) REFERENCES TACO(id);
ALTER TABLE TACO_INGREDIENTS ADD FOREIGN KEY (ingredients_id) REFERENCES INGREDIENT(id);

CREATE TABLE IF NOT EXISTS TACO_ORDER (
  id BIGINT UNIQUE GENERATED ALWAYS AS IDENTITY,
  placed_at TIMESTAMP NOT NULL,
  name VARCHAR(50) NOT NULL,
  street VARCHAR(50) NOT NULL,
  city VARCHAR(50) NOT NULL,
  state VARCHAR(2) NOT NULL,
  zip VARCHAR(10) NOT NULL,
  cc_number VARCHAR(16) NOT NULL,
  cc_expiration VARCHAR(5) NOT NULL,
  cvv VARCHAR(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS TACO_ORDER_TACOS (
  order_id BIGINT NOT NULL,
  tacos_id BIGINT NOT NULL
);

ALTER TABLE TACO_ORDER_TACOS ADD FOREIGN KEY (order_id) REFERENCES TACO_ORDER(id);
ALTER TABLE TACO_ORDER_TACOS ADD FOREIGN KEY (tacos_id) REFERENCES TACO(id);