apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: some-other-pvc
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-csi
  volumeName: eks-ci-01
  resources:
    requests:
      storage: 1Gi
