apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-playground-dev-8
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  volumeName: infra-playground-dev-8
  resources:
    requests:
      storage: 1Gi
