# Default values for simplest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
test:
  env:
    SOME_ENV_VAR: 'some value'
    SOME_OTHER_ENV_VAR: 'some other value'

