apiVersion: v1
kind: Pod
metadata:
  name: 'httpd'
  labels:
    function: 'httpd'
spec:
  securityContext:
#    runAsNonRoot: true
#    runAsUser: 1000
  containers:
  - name: 'httpd'
    image: docker.io/ovidiufeodorov/httpd:latest
    securityContext:
      # runAsNonRoot: false
      # runAsUser: 2000
      # privileged: false
      capabilities:
        add:
          - SYS_TIME
        drop:
          - CHOWN


