#!/bin/bash

#GC_LOGGING_ARGS="-Xloggc:./$(date +'%y-%m-%d-%H.%M.%S')-gc.log -XX:+PrintGCDateStamps";

#java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005 -cp $(dirname $0)/target/main-1.jar io.novaordis.playground.Main $@


debug_args=""
args=""

while [ -n "$1" ]; do

    if [ "$1" = "-d" ]; then
        debug_args="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"
    else
        args="${args} $1"
    fi
    shift
done

java ${debug_args} -cp $(dirname $0)/target/main-1.jar io.novaordis.playground.Main ${args}
