#!/bin/bash

GC_LOGGING_ARGS="-Xloggc:./$(date +'%y-%m-%d-%H.%M.%S')-gc.log -XX:+PrintGCDateStamps";

#java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005 -cp $(dirname $0)/target/main-1.jar io.novaordis.playground.Main $@
java -cp $(dirname $0)/target/main-1.jar ${GC_LOGGING_ARGS} io.novaordis.playground.Main $@
