apiVersion: v1
kind: Pod
metadata:
  name: 'httpd2'
spec:
  containers:
  - name: 'httpd'
    image: docker.io/ovidiufeodorov/httpd:latest
    volumeMounts:
      - name: volume-1
        mountPath: /azurefile
  volumes:
    - name: volume-1
      persistentVolumeClaim:
        claimName: test-azurefile-1
