CREATE TABLE IF NOT EXISTS INGREDIENT (

  id VARCHAR(4) UNIQUE NOT NULL,
  name VARCHAR(25) NOT NULL,
  type VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS TACO (

  id BIGINT UNIQUE GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(50) NOT NULL,
  createdAt TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TACO_INGREDIENTS (

  taco BIGINT NOT NULL,
  ingredient VARCHAR(4) NOT NULL
);

ALTER TABLE TACO_INGREDIENTS ADD FOREIGN KEY (taco) REFERENCES TACO(id);

ALTER TABLE TACO_INGREDIENTS ADD FOREIGN KEY (ingredient) REFERENCES INGREDIENT(id);

CREATE TABLE IF NOT EXISTS TACO_ORDER (

  id BIGINT UNIQUE GENERATED ALWAYS AS IDENTITY,
  deliveryName VARCHAR(50) NOT NULL,
  deliveryStreet VARCHAR(50) NOT NULL,
  deliveryCity VARCHAR(50) NOT NULL,
  deliveryState VARCHAR(2) NOT NULL,
  deliveryZip VARCHAR(10) NOT NULL,
  ccNumber VARCHAR(16) NOT NULL,
  ccExpiration VARCHAR(5) NOT NULL,
  ccCVV VARCHAR(3) NOT NULL,
  placedAt TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TACO_ORDER_TACOS (

  tacoOrder BIGINT NOT NULL,
  taco BIGINT NOT NULL
);

ALTER TABLE TACO_ORDER_TACOS ADD FOREIGN KEY (tacoOrder) REFERENCES TACO_ORDER(id);

ALTER TABLE TACO_ORDER_TACOS ADD FOREIGN KEY (taco) REFERENCES TACO(id);