#!/usr/bin/env bash

for l in $(java --list-modules); do
  l=${l%@*}
  IFS="$(printf '\n\r')"
  for e in $(java --describe-module "${l}"); do
    [[ ! ${e} =~ ^exports ]] && continue
    pn=${e#exports }
    if [[ ${pn} =~ com.sun.org ]]; then
      echo "${l} ${pn}"
    fi
  done
  IFS="$(printf ' \t\n')"
done
