apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cm-playground-of
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-csi
  volumeMode: Filesystem
  volumeName: cm-playground-of
