apiVersion: v1
kind: Pod
metadata:
  name: 'scriptless-loop'
spec:
  securityContext:
    #runAsUser: 0
    #runAsGroup: 0
    runAsUser: 1111
    runAsGroup: 2222
    fsGroup: 3333
  containers:
  - name: 'scriptless-loop'
    image: docker.io/ovidiufeodorov/scriptless-loop:latest
    volumeMounts:
      - name: volume-1
        mountPath: /data/volume-1
        subPath: dir1
      - name: volume-2
        mountPath: /data/volume-2
  volumes:
    - name: volume-1
      persistentVolumeClaim:
        #claimName: cm-playground-of-ap1
        claimName: cm-playground-of
    - name: volume-2
      emptyDir: {}



