apiVersion: v1
kind: Pod
metadata:
  name: 'scriptless-loop'
spec:
  securityContext:
    runAsUser: 1111
    runAsGroup: 2222
    fsGroup: 3333
  containers:
  - name: 'scriptless-loop'
    image: docker.io/ovidiufeodorov/scriptless-loop:latest
    volumeMounts:
      - name: volume-1
        mountPath: /data
  volumes:
    - name: volume-1
      hostPath:
        path: /Users/ovidiu/tmp/test
        type: Directory



