#!/usr/bin/env bash

#
# A Java application Unix shell wrapper.
#
# It is intended to be initially processed by Gradle Application Plugin SimpleTemplateEngine, as a template.
# The Application Plugin produces the final script for distribution with the application.
#

[ -f \$(dirname \$0)/bash.shlib ] && . \$(dirname \$0)/bash.shlib || { echo "\$(dirname \$0)/bash.shlib not found" 1>&2; exit 1; }

APP_HOME=\$(dirname \$0)/..
MAIN_CLASS=$mainClassName
CLASSPATH=$classpath

main "\$@"
