#!/usr/bin/env bash

context=default/api-nnqreelp-eastus2-aroapp-io:6443/kube:admin
namespace=of

[[ $(kubectl config current-context) != "${context}" ]] && { echo "not in right context: ${context}" 1>&2; exit 1; }

helm -n ${namespace} install cassandra bitnami/cassandra -f ./openshift-cassandra-overlay.yaml
