apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  description: 'this is a simple task'
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo "Hello World"