apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
data:
  shape: c3F1YXJlCg==
  size: bGFyZ2U=
---
apiVersion: v1
kind: Pod
metadata:
  name: 'scriptless-loop'
spec:
  securityContext:
    runAsUser: 1111
    runAsGroup: 2222
    fsGroup: 3333
  containers:
  - name: 'scriptless-loop'
    image: docker.io/ovidiufeodorov/scriptless-loop:latest
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/test-secret
        readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
        defaultMode: 0400




