#!/usr/bin/env bash

# shellcheck disable=SC2086,SC2015
[[ -f "$(dirname $0)/src/main/bash/lib/bash.shlib" ]] && source "$(dirname $0)/src/main/bash/lib/bash.shlib" || { echo "$(dirname $0)/src/main/bash/lib/bash.shlib not found" 1>&2; exit 1; }

function main() {
  # shellcheck disable=SC2015
  process-common-arguments "$@" && set -- "${ARGS[@]}" || fail "failed to process common arguments"
  local command=$1
  do-${command}

}

main "$@"