#!/usr/bin/env bash

httpd_port=${1:-"80"}

#
# some times we get "tcp://10.101.75.155:80" for HTTPD_PORT
#
if [[ ${httpd_port:0:6} = "tcp://" ]]; then
    httpd_port="80"
fi
echo "uid: $(id -u), gid: $(id -g)"
echo "using httpd port ${httpd_port}"

if [[ -z ${NO_INDEX_UPDATE} ]]; then
  #
  # Update index.html with port and address
  #
  target_file=/usr/local/apache2/htdocs/index.html
  echo "updating ${target_file}"
  addr=$(ip addr show dev eth0 | grep inet | awk '{print $2}')
  addr=${addr%/*}
  echo "address ${addr}"
  sed -i 's/^IP address:.*$/IP address: '${addr}':'${httpd_port}'/' ${target_file}
fi
#
# Update httpd.conf with new port
#
if [[ ${httpd_port} != "80" ]]; then
  sed -i 's/^Listen .*$/Listen '${httpd_port}'/' /usr/local/apache2/conf/httpd.conf && echo "httpd will listen on ${httpd_port}"
fi
