#!/usr/bin/env bash

# shellcheck disable=SC2086,SC2015
[[ -f "$(dirname $0)/lib/bash.shlib" ]] && source "$(dirname $0)/lib/bash.shlib" || { echo "$(dirname $0)/lib/bash.shlib not found" 1>&2; exit 1; }

URL="http://localhost:8080"
URL="http://localhost"

function main() {
  # shellcheck disable=SC2015
  process-common-arguments "$@" && set -- "${ARGS[@]}" || fail "failed to process common arguments"
  local command=$1
  do-${command}
}

function do-status() {
  local url="${URL}/status"
  (set -o pipefail; curl -s "${url}" | jq) || fail "failed to execute curl ${url}"
}

main "$@"