#!/usr/bin/env bash

local_jenkins_home=/Users/ovidiu/tmp/jenkins_home

docker run \
 --rm \
 --name jenkins \
 -p 8080:8080 \
 -v ${local_jenkins_home}:/var/jenkins_home \
 --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
 jenkins-with-plugins
