@Library('c3@task/of/PLAT-33422') _

properties([
        parameters([
                string(name: 'shape', defaultValue: 'square', description: 'The build shape'),
                string(name: 'color', defaultValue: 'red', description: 'The build color')
        ])
])

print "params: ${this.params}"
print "shape: " + this.params.shape
print "color: " + this.params.color

String NODE_LABEL = 'infra-worker-2.1.0'

node(NODE_LABEL) {

        sh 'echo shape: ${shape}'
        sh '''
                echo ">${shape}<"
        '''.stripIndent()
}


